# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindowui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(590, 346)
        MainWindow.setMinimumSize(QtCore.QSize(590, 346))
        MainWindow.setMaximumSize(QtCore.QSize(590, 346))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 51, 280, 31))
        self.label.setStyleSheet("font: 12pt \"PMingLiU-ExtB\";\n"
"font: 75 14pt \"Arial\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 81, 210, 20))
        self.label_2.setStyleSheet("font: 75 10pt \"Arial\";\n"
"font: 75 8pt \"Arial\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButtonAimer = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAimer.setGeometry(QtCore.QRect(27, 140, 130, 90))
        self.pushButtonAimer.setObjectName("pushButtonAimer")
        self.pushButtonReaction = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonReaction.setGeometry(QtCore.QRect(228, 140, 130, 90))
        self.pushButtonReaction.setObjectName("pushButtonReaction")
        self.pushButtonKeyboard = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonKeyboard.setGeometry(QtCore.QRect(427, 140, 130, 90))
        self.pushButtonKeyboard.setObjectName("pushButtonKeyboard")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 590, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Welcome to the test app !!"))
        self.label_2.setText(_translate("MainWindow", "You Can Choose some test to do"))
        self.pushButtonAimer.setText(_translate("MainWindow", "Aimer"))
        self.pushButtonReaction.setText(_translate("MainWindow", "Reaction Time"))
        self.pushButtonKeyboard.setText(_translate("MainWindow", "Keyboard Speed"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
